version: '3.8'

services:
  fpl-chatbot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - PORT=8080
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/__pycache__
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
